server:
  port: 7111
  servlet:
    context-path: /sl
  connection-timeout: 20000
  tomcat:
    max-connections: 60
    min-spare-threads: 6
    uri-encoding: UTF-8

spring:
  application:
    name: adx-core-master
  datasource:
    url: jdbc:mysql://172.27.117.22:3306/ad_sp?autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: maofather147
    tomcat:
      max-active: 5
      min-idle: 1
      initial-size: 1
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    messages:
      encoding: UTF-8

  jackson:
    default-property-inclusion: non_null

  #kafka
  kafka:
    bootstrap-servers: 172.27.117.22:9092
    #    listener:   172.27.117.22:9095,172.27.117.22:9096,172.27.117.22:9097   172.27.117.22:9092
    #      concurrency: 5 #指定listener 容器中的线程数，用于提高并发量
    #      ack-mode: manual_immediate #listner负责ack，每调用一次，就立即commit
    producer:
      batch-size: 50000 # 每次批量发送消息的数量
      retries: 3
      client-id: 200
      buffer-memory: 33554432 # 设置生产者内存缓冲区的大小
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 键的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # 值的序列化方式
      acks: 1

  redis:
    #    cluster:
    #      max-redirects: 3  # 获取失败 最大重定向次数
    #      nodes: 49.232.91.191:6379,81.70.178.200:6379,82.156.126.248:6379,49.232.74.185:6379,49.233.44.47:6379,152.136.194.147:6379
    #          password: 0UKPqK2u
    #      nodes: 8.140.99.234:7010,8.140.99.234:7011,8.140.99.234:7012,8.140.99.234:7013,8.140.99.234:7014,8.140.99.234:7015
    host: 172.27.117.22 # 172.27.117.22  123.56.174.234
    port: 6379
    password: Mzs147.
    database: 0
    timeout: 1000 #超时时间
    # 配置文件中添加 lettuce.pool 相关配置，则会使用到lettuce连接池
#    lettuce:
#      pool:
#        max-wait: 500 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 10 # 连接池中的最大空闲连接 默认 8
#        min-idle: 5 # 连接池中的最小空闲连接 默认 0
#        max-active: 10 # 连接池最大连接数（使用负值表示没有限制） 默认 8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mk.adx.vo

logging:
  file:
    max-size: 50MB # 日志文件的最大大小。默认为 20MB
    max-history: 1 # 日志文件要保留的归档的最大天数。默认为 7 天
  path: logs
  level:
    root: error

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8008/eureka/
      instance:
        lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
        lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}


feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"



